org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Versions: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.35-beta

mod_id=safeplots
mod_name=SafePlots
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.safemc.safeplots
